# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa720b0f83d7c6c9245dd82de9e3210c4dbb4fbd5ed9a36de5bb906a61ca7a9af51ff1886b4ba976ac7e417d8441a230a3a5c3fa019525b269b405c2226e2235

test:
  secret_key_base: 5bcfad205da5331ad14853b2045a7f93ce13b23a8a4fbf5dec5b8028d743198152aeba2c7430fa7f6d1ba9ccbb96b3036095fbca99f29e083d3fa4afaabbe0e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
